name: Linters

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #              run linters suite
      #----------------------------------------------
      - name: Run linters
        run: |
            source .venv/bin/activate
            flake8 --max-line-length=88 gateway/
            black --skip-string-normalization gateway
